baseURL = "https://js2264.github.io/scATACseq-workshop/"
publishDir = "docs"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Analysis of bulk and single-cell ATAC-seq datasets"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/js2264/scATACseq-workshop/blob/master/content/"
  packageBaseUrl = "scATACseq-workshop/"
  description = "Analysis of bulk and single-cell ATAC-seq datasets"
  author = "Jacques Serizay"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  titleSeparator = "::"
  themeVariant = "red"
  ordersectionsby = "title"
  disableSearch = true
  disableInlineCopyToClipBoard = true
  custom_css = ["css/custom_css.css"]

[blackfriday]
  hrefTargetBlank = true

[markup.highlight]
  style = "monokai"
