baseURL = "https://js2264.github.io/scATACseq-workshop/"
publishDir = "docs"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Analysis of bulk and single-cell ATAC-seq datasets"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/js2264/scATACseq-workshop/blob/master/content/"
  packageBaseUrl = "scATACseq-workshop/"
  description = "Analysis of bulk and single-cell ATAC-seq datasets"
  author = "Jacques Serizay"
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = true
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "red"
  ordersectionsby = "title"
  disableSearch = true

[blackfriday]
  hrefTargetBlank = true
